import { createHash } from 'node:crypto'
import { cp, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { buildAllContent } from '../../scripts/content/build-all'
import { createContentWorkspace } from '../../scripts/content/config'
import { applyKnowledgeUpdate } from '../../scripts/knowledge/apply-knowledge'
import { dryRunKnowledgeUpdate } from '../../scripts/knowledge/dry-run'

function hash(value: Buffer): string { return createHash('sha256').update(value).digest('hex') }
function u16(value: number): Buffer { const result = Buffer.alloc(2); result.writeUInt16LE(value); return result }
function u32(value: number): Buffer { const result = Buffer.alloc(4); result.writeUInt32LE(value); return result }
function crc32(value: Buffer): number { let crc = 0xffffffff; for (const byte of value) { crc ^= byte; for (let bit = 0; bit < 8; bit += 1) crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1 } return (crc ^ 0xffffffff) >>> 0 }
function zip(entries: Array<{ name: string; data: Buffer }>): Buffer { const local: Buffer[] = []; const central: Buffer[] = []; let offset = 0; for (const entry of entries) { const name = Buffer.from(entry.name); const crc = crc32(entry.data); const header = Buffer.concat([Buffer.from([80, 75, 3, 4]), u16(20), u16(0), u16(0), u16(0), u16(0), u32(crc), u32(entry.data.length), u32(entry.data.length), u16(name.length), u16(0), name, entry.data]); local.push(header); central.push(Buffer.concat([Buffer.from([80, 75, 1, 2]), u16(20), u16(20), u16(0), u16(0), u16(0), u16(0), u32(crc), u32(entry.data.length), u32(entry.data.length), u16(name.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), name])); offset += header.length } const directory = Buffer.concat(central); return Buffer.concat([...local, directory, Buffer.from([80, 75, 5, 6]), u16(0), u16(0), u16(entries.length), u16(entries.length), u32(directory.length), u32(offset), u16(0)]) }
async function fixture(): Promise<string> { const root = await mkdtemp(join(tmpdir(), 'myriad-apply-')); for (const path of ['src', 'schemas', 'generated'] as const) await cp(resolve(process.cwd(), path), resolve(root, path), { recursive: true }); await mkdir(resolve(root, 'public/media'), { recursive: true }); await buildAllContent({ workspace: createContentWorkspace(root, resolve(root, 'schemas')), targetRoot: resolve(root, 'public/_generated'), publicDirectory: resolve(root, 'public') }); await mkdir(resolve(root, 'inbox/batches'), { recursive: true }); return root }
async function batch(root: string): Promise<void> { const payload = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]); const manifest = Buffer.from(JSON.stringify({ schema_version: 1, batch_id: 'batch-20260731-001-apply', created_at: '2026-07-31T00:00:00.000Z', released_on: '2026-07-31', base_content_version: '2026.07.30-01', target_content_version: '2026.07.31-01', summary: 'apply test', operations: [{ operation_id: 'op-0001', action: 'add', kind: 'media', path: 'public/media/apply.png', entity_id: 'apply-media', payload_sha256: hash(payload) }] })); await writeFile(resolve(root, 'inbox/batches/batch-20260731-001-apply.zip'), zip([{ name: 'batch.json', data: manifest }, { name: 'payload/public/media/apply.png', data: payload }])) }

describe('knowledge apply flow', () => {
  it('applies a confirmed batch and updates publishing metadata', async () => { const root = await fixture(); await batch(root); const git = { head: 'test', clean: true }; const preview = await dryRunKnowledgeUpdate({ repositoryRoot: root, git }); const result = await applyKnowledgeUpdate({ repositoryRoot: root, confirmationToken: preview!.confirmation_token, git }); expect(result.targetVersion).toBe('2026.07.31-01'); await expect(readFile(resolve(root, 'generated/imported-batches.json'), 'utf8')).resolves.toContain('batch-20260731-001-apply'); await expect(readFile(resolve(root, 'inbox/processed/batch-20260731-001-apply.zip'))).resolves.toBeTruthy(); await rm(root, { recursive: true, force: true }) }, 15_000)
  it('rejects stale confirmation tokens', async () => { const root = await fixture(); await batch(root); await expect(applyKnowledgeUpdate({ repositoryRoot: root, confirmationToken: 'APPLY:stale', git: { head: 'test', clean: true } })).rejects.toThrow('令牌'); await rm(root, { recursive: true, force: true }) })
  it('restores source and index if apply fails after operations', async () => { const root = await fixture(); await batch(root); const git = { head: 'test', clean: true }; const preview = await dryRunKnowledgeUpdate({ repositoryRoot: root, git }); await expect(applyKnowledgeUpdate({ repositoryRoot: root, confirmationToken: preview!.confirmation_token, git, onPoint: async () => { throw new Error('injected') } })).rejects.toThrow('injected'); await expect(readFile(resolve(root, 'generated/imported-batches.json'), 'utf8')).resolves.toContain('"batches": []'); await expect(readFile(resolve(root, 'public/media/apply.png'))).rejects.toMatchObject({ code: 'ENOENT' }); await rm(root, { recursive: true, force: true }) })
})
