import type { Taxonomy, ValidationResult } from './validate-source'

export function compileKnowledgeMap(result: ValidationResult, content_version: string) {
  const taxonomy = result.taxonomy as Taxonomy
  const nodes = [...result.nodes].sort((a, b) => a.data.domain_id.localeCompare(b.data.domain_id) || a.data.course_id.localeCompare(b.data.course_id) || a.sequence - b.sequence || a.data.id.localeCompare(b.data.id))
  const edges: Array<{ type: string; from: string; to: string; route_id?: string; role?: string }> = nodes.flatMap((node) => [...(node.data.prerequisites ?? []).map((id) => ({ type: 'prerequisite', from: id, to: node.data.id })), ...(node.data.related ?? []).map((id) => ({ type: 'related', from: node.data.id, to: id })), ...(node.data.qa?.parent_node_id ? [{ type: 'qa-parent', from: node.data.qa.parent_node_id, to: node.data.id }] : [])])
  for (const route of result.routes) for (const stage of route.stages) for (const module of stage.modules) for (const unit of module.units) edges.push({ type: 'route', from: route.id, to: unit.node_id, route_id: route.id, role: unit.role })
  edges.sort((a, b) => `${a.type}:${a.from}:${a.to}`.localeCompare(`${b.type}:${b.from}:${b.to}`))
  const qa_chains = nodes.filter((node) => node.data.qa).reduce<Array<{ chain_id: string; root_node_id: string; answer_ids: string[] }>>((all, node) => { const qa = node.data.qa!; const chain = all.find((entry) => entry.chain_id === qa.chain_id); if (chain) chain.answer_ids.push(node.data.id); else all.push({ chain_id: qa.chain_id, root_node_id: qa.root_node_id, answer_ids: [node.data.id] }); return all }, [])
  return { schema_version: 1 as const, content_version, domains: taxonomy.domains.map((domain) => ({ id: domain.id, name: domain.name, courses: domain.courses.map((course) => ({ id: course.id, name: course.name, node_ids: nodes.filter((node) => node.data.course_id === course.id).map((node) => node.data.id) })) })), nodes: nodes.map((node) => ({ id: node.data.id, domain_id: node.data.domain_id, course_id: node.data.course_id, sequence: node.sequence, kind: node.data.qa ? 'qa' as const : node.data.domain_id === 'knowledge-roaming' ? 'roaming' as const : 'normal' as const })), edges, routes: result.routes.map((route) => ({ id: route.id, code: route.code, node_ids: route.stages.flatMap((stage) => stage.modules.flatMap((module) => [...module.units].sort((a, b) => a.order - b.order).map((unit) => unit.node_id))) })), qa_chains }
}
